version: '3.6'
services:
  app:
    build: .
    expose:
      - 8080
      - 8081
    dns: 127.0.0.53
    dns_search: app.example.com


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      #- ./prometheus/:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      #- '--storage.tsdb.path=/prometheus/'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - prometheus
    ports:
      - "8080:8080"
      - "9090:9090"

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

